import {db,Mode} from '../../../lib/db';
import {jsPDF} from 'jspdf';
const money=(v:number)=>`₹${Math.round(Number(v)||0).toLocaleString('en-IN')}`;
const clean=(v:any)=>String(v??'').trim();
function words(n:number){const ones=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'];const tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];const u=(x:number)=>x<20?ones[x]:tens[Math.floor(x/10)]+(x%10?' '+ones[x%10]:'');const p=(x:number)=>x<100?u(x):ones[Math.floor(x/100)]+' Hundred'+(x%100?' '+u(x%100):'');n=Math.round(Math.max(0,n));if(n===0)return 'Zero';const o:string[]=[];const c=Math.floor(n/10000000);n%=10000000;const l=Math.floor(n/100000);n%=100000;const t=Math.floor(n/1000);n%=1000;if(c)o.push(p(c),'Crore');if(l)o.push(p(l),'Lakh');if(t)o.push(p(t),'Thousand');if(n)o.push(p(n));return o.join(' ')}
const on=(s:any,k:string)=>s?.[k]!==false;
export async function GET(req:Request){try{const u=new URL(req.url);const mode=(u.searchParams.get('mode')||'LIVE') as Mode;const id=Number(u.searchParams.get('id'));const companyId=Number(req.headers.get('x-aksh-company-id')||u.searchParams.get('company_id')||1);const d=await db(mode,companyId);const p=await d.prepare(`SELECT p.*,x.name party_name,x.address,x.contact,x.gst,x.pan,b.bank_name,b.account_number,b.ifsc,b.branch FROM payments p JOIN parties x ON x.id=p.party_id LEFT JOIN bank_accounts b ON b.party_id=x.id AND b.is_primary=1 WHERE p.id=?`).get(id) as any;if(!p)return new Response('Payment not found',{status:404});const a=await d.prepare(`SELECT q.sample_no,q.invoice_no,q.purchase_date,a.amount FROM payment_allocations a JOIN purchases q ON q.id=a.purchase_id WHERE a.payment_id=? ORDER BY q.purchase_date,q.id`).all(id) as any[];const company=await d.prepare('SELECT * FROM company_settings WHERE id=1').get() as any;let s:any={};try{s=JSON.parse(company?.payment_advice_settings||'{}')}catch{}
const doc=new jsPDF({unit:'mm',format:'a4'});const L=15,R=195;doc.setDrawColor(215,219,225);doc.setLineWidth(.35);doc.setFont('helvetica','bold');doc.setFontSize(20);doc.text(String(company?.entity_name||'SOLIVY'),L,20);doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text('PAYMENT ADVICE',L,27);doc.text(`Payment No: ${p.payment_no}`,R,27,{align:'right'});doc.line(L,31,R,31);
doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('PAYMENT DATE',L,40);doc.setFont('helvetica','normal');doc.text(String(p.payment_date),L,46);doc.setFont('helvetica','bold');doc.text('MODE',75,40);doc.setFont('helvetica','normal');doc.text(String(p.mode),75,46);if(on(s,'show_utr')){doc.setFont('helvetica','bold');doc.text('UTR / REFERENCE',130,40);doc.setFont('helvetica','normal');doc.text(clean(p.utr),130,46,{maxWidth:65})}
doc.roundedRect(L,53,180,39,2,2);doc.setFont('helvetica','bold');doc.text('PAID TO',L+5,61);doc.setFont('helvetica','normal');doc.setFontSize(11);doc.text(String(p.party_name||''),L+5,68);doc.setFontSize(8);if(on(s,'show_party_address')&&clean(p.address))doc.text(clean(p.address),L+5,75,{maxWidth:105});if(on(s,'show_party_gst')&&clean(p.gst))doc.text(`GSTIN: ${p.gst}`,L+5,83);if(on(s,'show_party_pan')&&clean(p.pan))doc.text(`PAN: ${p.pan}`,L+60,83);if(on(s,'show_bank_details')){doc.setFont('helvetica','bold');doc.text('SUPPLIER BANK',130,61);doc.setFont('helvetica','normal');if(clean(p.bank_name))doc.text(`Bank: ${p.bank_name}`,130,68);if(clean(p.account_number))doc.text(`A/C: ${p.account_number}`,130,75);if(clean(p.ifsc))doc.text(`IFSC: ${p.ifsc}`,130,82)}
let y=103;if(on(s,'show_allocations')){doc.setFillColor(244,246,248);doc.rect(L,y-7,180,9,'F');doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text('ALLOCATED BILL / SAMPLE',L,y);doc.text('AMOUNT',R,y,{align:'right'});y+=10;doc.setFont('helvetica','normal');for(const row of a){doc.text(`${row.invoice_no||'-'} / ${row.sample_no}`,L,y);doc.text(money(row.amount),R,y,{align:'right'});y+=7}if(!a.length){doc.setTextColor(100,105,110);doc.text('No purchase allocation recorded',L,y);doc.setTextColor(0,0,0);y+=7}y+=7}
doc.line(110,y,195,y);y+=8;doc.setFont('helvetica','normal');doc.text('Gross Settlement',120,y);doc.text(money(p.amount),R,y,{align:'right'});y+=7;if(on(s,'show_tds')){doc.text(`TDS (${Number(p.tds_rate||0)}%)`,120,y);doc.text(money(p.tds_amount),R,y,{align:'right'});y+=8}const displayedNet=on(s,'include_tds_in_net')?Number(p.net_paid??(Number(p.amount||0)-Number(p.tds_amount||0))):Number(p.amount||0);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('NET BANK PAYMENT',120,y);doc.text(money(displayedNet),R,y,{align:'right'});y+=15;
if(on(s,'show_amount_words')){doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text('AMOUNT IN WORDS',L,y);doc.setFont('helvetica','normal');doc.text(`${words(displayedNet)} Rupees Only`,L,y+6,{maxWidth:180});y+=20}
if(on(s,'show_broker')&&clean(p.broker_name)){doc.setFont('helvetica','bold');doc.text('BROKER',L,y);doc.setFont('helvetica','normal');doc.text(`${p.broker_name}${p.broker_email?' • '+p.broker_email:''}`,L,y+6);y+=15}if(on(s,'show_notes')&&clean(p.notes)){doc.setFont('helvetica','bold');doc.text('NOTES',L,y);doc.setFont('helvetica','normal');doc.text(clean(p.notes),L,y+6,{maxWidth:180})}
doc.setFontSize(7.5);doc.text('System-generated payment advice. It is not a bank confirmation or tax certificate.',L,270);doc.text(String(company?.entity_name||'SOLIVY'),R,270,{align:'right'});const bytes=new Uint8Array(doc.output('arraybuffer'));return new Response(bytes,{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="Payment-Advice-${p.payment_no}.pdf"`}})}catch(e:any){return new Response(e?.message||'Unable to generate payment advice',{status:500})}}
