import { sessionMode } from '../../../lib/db';
import {NextResponse} from 'next/server';
import {db,Mode} from '../../../lib/db';
function admin(req:Request){return req.headers.get('x-aksh-role')==='ADMIN'}
const DEFAULTS={commercial_bill:{show_invoice_no:true,show_reference_no:true,show_buyer_order_no:true,show_payment_terms:true,show_other_references:true,show_sample_no:true,show_delivery_terms:true,show_hsn:true,show_quantity:true,show_rate:true,show_amount:true,show_unload:true,show_driver_rokdi:true,show_freight:true,show_moisture:true,show_discount:true,show_quality_deduct:true,show_other_charges:true,show_gross_weight:true,show_net_weight:true,show_party_contact:true,show_party_gst:true,show_party_pan:true,show_company_address:true,show_company_email:true,show_company_gst:true,show_company_pan:true,show_bank_details:true,show_declaration:true,show_signature:true,include_unload:true,include_driver_rokdi:true,include_freight:true,include_moisture:true,include_discount:true,include_quality_deduct:true,include_other_charges:true},third_party_bill:{show_invoice_no:true,show_reference_no:true,show_buyer_order_no:true,show_payment_terms:true,show_other_references:true,show_sample_no:true,show_delivery_terms:true,show_hsn:true,show_quantity:true,show_rate:true,show_amount:true,show_gross_weight:true,show_net_weight:true,show_party_contact:true,show_party_gst:true,show_party_pan:true,show_company_address:true,show_company_email:true,show_company_gst:true,show_company_pan:true,show_bank_details:true,show_declaration:true,show_signature:true,include_unload:true,include_driver_rokdi:true,include_freight:true,include_moisture:true,include_discount:true,include_quality_deduct:true,include_other_charges:true},payment_advice:{show_party_address:true,show_party_gst:true,show_party_pan:true,show_bank_details:true,show_broker:true,show_utr:true,show_tds:true,show_allocations:true,show_notes:false,show_amount_words:true,show_net_weight:true,show_bags:true,show_gross_weight:false,show_gross_amount:false,show_discount_percent:true,show_allocated:false,show_outstanding:true,show_payment_date_below_words:true,show_utr_below_words:true,show_payment_date_top:false,show_gross_settlement:false,show_allocated_total:false,show_unallocated:false,include_tds_in_net:true}};
function read(d:any){
 const r=d.prepare('SELECT commercial_bill_settings,payment_advice_settings,third_party_bill_settings FROM company_settings WHERE id=1').get() as any;
 let a:any={},b:any={},c:any={};
 try{a=JSON.parse(r?.commercial_bill_settings||'{}')}catch{}
 try{b=JSON.parse(r?.payment_advice_settings||'{}')}catch{}
 try{c=JSON.parse(r?.third_party_bill_settings||'{}')}catch{}
 return {commercial_bill:{...DEFAULTS.commercial_bill,...a},third_party_bill:{...DEFAULTS.third_party_bill,...c},payment_advice:{...DEFAULTS.payment_advice,...b}}
}
export async function GET(req:Request){try{if(!admin(req))throw Error('Admin access required');const u=new URL(req.url);const d=db(sessionMode(req),Number(req.headers.get('x-aksh-company-id')||u.searchParams.get('company_id')||1));return NextResponse.json(read(d))}catch(e:any){return NextResponse.json({error:e.message},{status:403})}}
export async function POST(req:Request){try{if(!admin(req))throw Error('Admin access required');const x=await req.json();const d=db(sessionMode(req),Number(req.headers.get('x-aksh-company-id')||x.company_id||1));const current=read(d);const cb={...current.commercial_bill,...(x.commercial_bill||{})};const tp={...current.third_party_bill,...(x.third_party_bill||{})};const pa={...current.payment_advice,...(x.payment_advice||{})};d.prepare(`UPDATE company_settings SET commercial_bill_settings=?,third_party_bill_settings=?,payment_advice_settings=?,updated_at=CURRENT_TIMESTAMP WHERE id=1`).run(JSON.stringify(cb),JSON.stringify(tp),JSON.stringify(pa));return NextResponse.json({ok:true,commercial_bill:cb,third_party_bill:tp,payment_advice:pa})}catch(e:any){return NextResponse.json({error:e.message},{status:400})}}
